import { LinkedList } from '../structure'

const linkedListItem = new LinkedList()
linkedListItem.append('第一个元素')
linkedListItem.append('第二个元素')
linkedListItem.append('第三个元素')
linkedListItem.append('第四个元素')
linkedListItem.removeAt(2)
console.log(linkedListItem.toString())
linkedListItem.append('第五个元素')
linkedListItem.removeAt(0)
console.log(linkedListItem.toString())
linkedListItem.removeAt(10)
console.log(linkedListItem.toString())
linkedListItem.append('第六个元素')
linkedListItem.append('第七个元素')
linkedListItem.append('第八个元素')

console.log(linkedListItem.toString())
linkedListItem.insert(0, '头部插入')
console.log(linkedListItem.toString())
linkedListItem.insert(2, '中间插入')
console.log(linkedListItem.toString())
linkedListItem.insert(8, '尾部插入')
console.log(linkedListItem.toString())

console.log(linkedListItem.indexOf('头部插入'))
console.log(linkedListItem.indexOf('第四个元素'))
console.log(linkedListItem.indexOf('尾部插入'))
console.log(linkedListItem.indexOf('不存在的元素'))

console.log(linkedListItem.remove('中间插入'))
console.log(linkedListItem.toString())
console.log(linkedListItem.remove('不存在的元素'))
console.log(linkedListItem.toString())
